server:
  affinity: ""
  ha:
    enabled: true
    raft: 
      enabled: true
      # config: |
      #   storage "raft" {
      #       path = "/data"
      #     }
  dataStorage:
    enabled: true
    # Size of the PVC created
    size: 5Gi
    # Location where the PVC will be mounted.
    mountPath: "/vault/data"
    # Name of the storage class to use.  If null it will use the
    # configured default Storage Class.
    storageClass: null
    # Access Mode of the storage device being used for the PVC
    accessMode: ReadWriteOnce
    # Annotations to apply to the PVC
    annotations: {}

