kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: manual
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/disk/by-path/pci-0000:00:06.0
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hostname
                operator: In
                values:
                - minikube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: manual
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/disk/by-path/pci-0000:00:07.0
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hostname
                operator: In
                values:
                - minikube

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  storageClassName: manual
  capacity:
    storage: 10
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/disk/by-path/pci-0000:00:08.0
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hostname
                operator: In
                values:
                - minikube